# Generated by Django 3.2.15 on 2022-11-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeservice_app.nursery'),
        ),
    ]
